name: Deploy Runtime (App + ECS)

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "docker/**"
      - "infra/lib/runtime/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-runtime:
    runs-on: ubuntu-latest

    steps:

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::949967577049:role/ecs-kinesis-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      
      # ----------------------------
      # CREATE IMAGE TAG (Git SHA)
      # ----------------------------
      - name: Compute image tag
        id: vars
        run: |
          echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile -t kinesis-consumer:${{ env.IMAGE_TAG }} .

      - name: Tag & push Docker image to ECR
        run: |
          docker tag kinesis-consumer:${{ env.IMAGE_TAG }} \
            949967577049.dkr.ecr.us-east-1.amazonaws.com/kinesis-consumer:${{ env.IMAGE_TAG }}

          docker push \
            949967577049.dkr.ecr.us-east-1.amazonaws.com/kinesis-consumer:${{ env.IMAGE_TAG }}
      
      - name: Clean install CDK dependencies
        working-directory: infra
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Install CDK dependencies
        working-directory: infra
        run: npm install

      - name: Deploy Runtime stack (ECS)
        working-directory: infra
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          npx cdk deploy Runtime-EcsStack --require-approval never